# Unix submit description file

executable              = snap_fie_processing.sh                                    
arguments               = $(config_file) $(Item) $(pot) 
log                     = $(ClusterId)test_snap.log
output                  = $(ClusterId)test_snap.out
error                   = $(ClusterId)test_snap.err
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
notify_user             = federico.battisti@bo.infn.it
notification            = Always
queue 1